### ISSUE TITLE
Can I add to this plugin optional argument '-nx'?

### ISSUE THREAD

**Issue by oivva** [imagemin/imagemin-optipng#10]
From [user manual](http://optipng.sourceforge.net/optipng-0.7.6.man.pdf):
−nx Do not apply any lossless image reduction: enable the options −nb, −nc and −np.

**Comment by sindresorhus** [comment]
What's the point of using this plugin if you're gonna disable the minifying?

**Comment by oivva** [comment]
This setting doesn't disable the minifying at all, it just disable image reduction. It's pretty similar to optimizationLevel: 0, but gives less size when it's using with optimizationLevel: 3.

Or better to add 3 optional arguments: 

−nb Do not apply bit depth reduction.
−nc Do not apply color type reduction.
−np Do not apply palette reduction.

because −nx enable all theme: −nb, −nc and −np.

**Comment by sindresorhus** [comment]
Sure. PR welcome. The options should use a real words, no acronyms, and come with doc changes.
