### ISSUE TITLE
Using false for bitDepthReduction, colorTypeReduction, or paletteReduction causes error

### ISSUE THREAD

**Issue by jdalton** [imagemin/imagemin-optipng#12]
Using `false` for bitDepthReduction, colorTypeReduction, or paletteReduction causes an error:
```shell
** Error: The option -out requires one input file
```

~~I'm guessing `execBuffer.input` should be last.~~

Moving the `execBuffer.input` lower or a combination of them lower doesn't help.
I tried manually executing optipng with the settings and it executed without error. Maybe it's something funky with the temp files used as input/output destinations?

**Comment by jdalton** [comment]
I'm guessing `execBuffer.input` should be last.

**Comment by jdalton** [comment]
Moving the `execBuffer.input` lower or a combination of them lower doesn't help.
I tried manually executing optipng with the settings and it executed without error. Maybe it's something funky with the temp files used as input/output destinations?

**Comment by kevva** [comment]
Interesting. I'll have a look.

**Comment by jdalton** [comment]
I noticed it part way through processing a collection of images but it errors consistently.

**Comment by kevva** [comment]
Weirdly enough, the following works, but when pushing them it doesn't:

```js
[
    '-nb',
    '-nc',
    '-np',
    '-strip', 'all',
    '-clobber',
    '-fix',
    '-o', opts.optimizationLevel,
    '-out', execBuffer.output,
    execBuffer.input
]
```

**Comment by jdalton** [comment]
That's b-a-n-a-n-a-s

**Comment by jdalton** [comment]
Ok so I narrowed it down a bit more. They work if defined in the array literal regardless of order.
The bug is something with V8 symbols and Array#push.

Converting:
```js
	if (!opts.bitDepthReduction) {
		args.push('−nb');
	}

	if (!opts.colorTypeReduction) {
		args.push('−nc');
	}

	if (!opts.paletteReduction) {
		args.push('−np');
	}
```
to
```js
	if (!opts.bitDepthReduction) {
		args[args.length] = '-nb';
	}

	if (!opts.colorTypeReduction) {
		args[args.length] = '-nc';
	}

	if (!opts.paletteReduction) {
		args[args.length] = '-np';
	}
```
fixes the issue.

The symbol reference appears to still be `===` using `Array#push` so not super sure what's up.

**Comment by jdalton** [comment]
With or without the change the symbols look to be found in `exec-buffer` so it's not erroring on ```js
opts.args = opts.args.map(x => x === input ? inputPath : x === output ? outputPath : x);
```
The results look identical there too. Something odd (smells like a JIT bug since it happens after a few of the images are processed.

**Comment by jdalton** [comment]
BTW this seems to fix the issue in Node 6 but not Node 4.

**Comment by jdalton** [comment]
Oops the fix works in Node v4 too. It came down to tabs vs spaces. It means this is really looking like a V8 JIT bug as tabs vs spaces can hit differently in its ~600 char inline limit.

**Comment by kevva** [comment]
Hmm, that's interesting. I wonder why the same doesn't happen in here for example https://github.com/imagemin/imagemin-pngquant/blob/master/index.js.

**Comment by jdalton** [comment]
\cc @caitp

**Comment by jdalton** [comment]
Ok so narrowed it down further. It looks like it could be whitespace related:
```
	if (!opts.bitDepthReduction) {
		args.push('−nb');
	}

	if (!opts.colorTypeReduction) {
		args.push('−nc');
	}

	if (!opts.paletteReduction) {
		args.push('−np');
	}
```
to this then it works:
```js
    if (!opts.bitDepthReduction) {
        args.push('-nb');
    }

    if (!opts.colorTypeReduction) {
        args.push('-nc');
    }

    if (!opts.paletteReduction) {
        args.push('-np');
    }
```

**Comment by jdalton** [comment]
first one is tabs, second is spaces.

**Comment by phpnode** [comment]
@jdalton does the second fail when you run node with `--max_inlined_source_size=5000`?

**Comment by caitp** [comment]
Sounds interesting, do you think you could file this on https://bugs.chromium.org/p/v8?

Also, I'm guessing this has been reproduced on Node.js nightlies, but correct me if I'm wrong :)

**Comment by jdalton** [comment]
@phpnode 
> does the second fail when you run node with `--max_inlined_source_size=5000`?
```js
node --max_inlined_source_size=5000 ./node_modules/gulp/bin/gulp.js build
```
still errors.

**Comment by jdalton** [comment]
Reported https://bugs.chromium.org/p/v8/issues/detail?id=5383.

**Comment by caitp** [comment]
Thanks --- could you provide basic repro steps?

**Comment by jdalton** [comment]
Sure. I'd like to get another confirm though before digging a bit more. \@kevva can you verify if changing the snippets in https://github.com/imagemin/imagemin-optipng/issues/12#issuecomment-246752245 makes things work.

**Comment by caitp** [comment]
It would not be surprising at all if the space-to-tab conversion made things work (as noted by Camillo and @phpnode, this exhausts various thresholds eg inlining heuristics, eager compilation heuristics, etc. Which tells me that whichever backend is doing the work when the threshold is not exceeded, is/was doing something wrong. This may have already been fixed upstream, but not ported into Node 5.1.

**Comment by kevva** [comment]
@jdalton, still don't work for me, even when converting to spaces.

**Comment by jdalton** [comment]
I've created a reduced repro here:
https://github.com/jdalton/v8-bug-5383

**Comment by caitp** [comment]
In agreement with @kevva --- at least on a mac with node 6.0.0, 4.0.0, and the sept 12 nightly, I haven't been able to circumvent the error by either replacing tabs with spaces, or increasing --max-inlined-source-size.

**Comment by caitp** [comment]
I don't think the issue is with Array#push() being inlined incorrectly, or with imageminOptipng being inlined incorrectly.

There seems to be 2 issues:

1) inserting `-nb` and etc after the "files" options does not seem to obey the contract of the optipng programme, moving these options to before the main arguments works correctly when run from the shell.

2) the above fix actually doesn't fix the `gulp build` in the repro, but, I'll do a bit more debugging to isolate the problem there. This may not apply to all platforms, so I would suggest sending a pull request to update the argument building to match the contract for the optipng binary and trying it out

**Comment by kevva** [comment]
@caitp, I've tried that already by doing this and adding the default arguments after the checks:

```js
const args = [];

// checks here

args = args.concat(...);
```

It fails anyway.

**Comment by caitp** [comment]
see above, there is definitely another problem, but it is not related to populating the array. The array does get populated correctly, and this is observable via `NODE_DEBUG=spawn gulp build`, for example

**Comment by kevva** [comment]
@caitp, yeah, I know, but have a look at https://github.com/imagemin/imagemin-optipng/issues/12#issuecomment-246609562.

If I modify the code to push the arguments in exactly that order, it doesn't wor. But if I skip pushing them and include them in the array by default, it works, even though both the arrays looks exactly the same.

**Comment by caitp** [comment]
I've found another fun fact:

The `-` character seems to be U+2212 (MINUS-SIGN) rather than U+002D (HYPHEN-MINUS). This results in optipng adding an extra argument interpreted as a file, and fails the "only 1 file_count" assertion.

**Comment by jdalton** [comment]
Ah that could explain why the copy/pasting editing stuff was working if that changed encoding from one source to the next!

**Comment by jdalton** [comment]
Thank you for digging in @caitp!

**Comment by jdalton** [comment]
Moved to #13.

**Comment by caitp** [comment]
Cheers =)

**Comment by kevva** [comment]
@caitp, great effort :). That explains everything. The `U+2212 (MINUS-SIGN)` came from a PR (https://github.com/imagemin/imagemin-optipng/pull/11) which went untested.
