### ISSUE TITLE
Single PNG file always causes decoder error in IE11

### ISSUE THREAD

**Issue by alexjalex** [imagemin/imagemin-optipng#19]
I have lots of PNG files that work as expected. All processed in the exact way and settings from Photoshop. However just 1 file causes a decoder error in IE11.

**PLEASE NOTE:** The following images are white on transparent, so not visible here with white background.

**Original file. RGB, exported from photoshop.**
![logo_normal](https://user-images.githubusercontent.com/11192565/45607582-c0f2e180-ba90-11e8-852e-836d2df83ca8.png)

**Optimized output that causes error**
![logo_normal](https://user-images.githubusercontent.com/11192565/45607613-f3044380-ba90-11e8-82dc-9de30d7482a9.png)

**Comment by sindresorhus** [comment]
If there's a problem in IE11, it's a problem in the actual OptiPNG binary, which is out of our control.
