### ISSUE TITLE
On Freebsd 10 (x64), we cannot use the optipng in the vendor folder

### ISSUE THREAD

**Issue by starchen** [imagemin/imagemin-optipng#4]
~~I'm getting a "ELF interpreter /libexec/ld-elf.so.1 not found" when I try to minify images using optipng since the changes on  the 4.3.0 that occured around the 06/06/2015.~~ -> We added the 32-bit compatibility on our Freebsd10 systems, and it works now. 

However, we installed a custom optipng on our system. Is it possible to tell the plugin to use the system-wide optipng  instead of the one shipped in the vendor folder?

**Comment by kevva** [comment]
Yes, `bin-wrapper` will support global binaries very soon. Going to close this as it sounds like you got it working :).
